#! /bin/bash

# To rebuild an image that is already running, you will have to uncomment the line below:
# docker stop codePlatoon && docker rm codePlatoon && /

docker pull codeplatoon/base && /
docker run -it --name codePlatoon -v "$(pwd)":/usr/local/src/code_platoon -v "$(pwd)"/.bashrc:/root/.bashrc codeplatoon/base
